### PR TITLE
Add Firefox support

### PR DESCRIPTION
**Pull request by nt1m**

### CODE REVIEW

**Comment by nt1m** [comment]
Hi @elliotaplant @dank93 ,

This adds Firefox support to the extension without breaking the Chrome extension.

Please consider uploading it to https://addons.mozilla.org/en-US/firefox/ when merged :)

**Comment by nt1m** [comment]
@elliotaplant @dank93 Friendly reminder about this PR, please look at it :)

**Comment by dank93** [comment]
Hi Tim, thanks so much for contributing! This week is pretty swamped for
me, I'll take a look over the weekend.

Cheers,

Daniel

**Comment by nt1m** [comment]
@dank93 @elliotaplant Any update? This PR is pretty simple :) I've tested on both Chrome and Firefox.

**Comment by nt1m** [comment]
@dank93 @elliotaplant Any update :)) It's just a 2 line PR.

**Comment by nt1m** [comment]
@dank93 @elliotaplant Please review this :) I already tested this on both Chrome and Firefox, and it's only a two line change.

**Comment by elliotaplant** [comment]
Reviewed and merged! Would you like to put it in the Firefox addons store, or should we?

**Comment by nt1m** [comment]
@elliotaplant Thanks! Since it's your add-on, you should probably do it so your names are credited as add-on authors, I'd feel guilty putting your awesome work under my name :)

But if you don't have to time to do so, please let me know and I'll publish it under my account (which means I'll be listed as author).

**Comment by elliotaplant** [comment]
Sounds good. I'll put it up tomorrow.

**Comment by elliotaplant** [comment]
Histree is in the FireFox store! https://addons.mozilla.org/en-US/developers/addon/histree
Thanks so much for your help @nt1m. I had to change the way we register page location changes because firefox doesn't do a full page reload when the user clicks the back button. However, that change optimized the way the extension works in chrome so now it should be faster and better registering location changes in both browsers!

**Comment by nt1m** [comment]
@elliotaplant Thanks! Your latest changes work great on Firefox, but it seems to break the chrome version, made #9 to fix that :)

Also, note that you're Anonymous user 4cb6cb on  https://addons.mozilla.org/en-US/firefox/addon/histree/ :))

**Comment by elliotaplant** [comment]
Thanks for the heads up @nt1m! I added a username on FireFox.

**Pull request merged**
